### ISSUE TITLE
Does the WordLlama model have any requirements or limitations on the length of the input text?

### ISSUE THREAD

**Issue by yhfwww** [dleemiller/WordLlama#44]
WordLlama is really a good choice. 
But I have a question during use and couldn't find the answer in the code repository. 
The question is: Do WordLlama models have any requirements or limitations on the length of input text?

**Comment by dleemiller** [comment]
Great questions. There is no specific limitation to the length of text. It does not require any positional encoding, since it just uses static embeddings and average pooling.

However, depending on how long you are interested in encoding, the performance may fall off for long texts. The training is done on sentence transformer datasets, which are primarily text segments that are a few hundred tokens at most.
